### PR TITLE
Fix escaping BashWrapper pipe characters being stripped

### LINKED ISSUE #421: Viash config inject on a Nextflow script mangles the content
While viash config inject on a Nextflow script doesn't currently contribute much, it shouldn't mangle it.

```
workflow main_wf {
  main:
    | foo
    | bar
}
```

gets replaced with:
```
workflow main_wf {
  main:
 foo
 bar
}

```

### PR DESCRIPTION
**Pull request by Grifs**
## Describe your changes

Fix escaping BashWrapper pipe characters being stripped

Fix escaping of the included script where a line starting with a pipe character with optional leading spaces is stripped of the leading spaces and pipe character.

Add a function that escapes pipe characters (with leading spaces) and use where stripMargin is called on the script.

## Issue ticket number and link
Closes #421 

## Checklist before requesting a review
- [x] I have performed a self-review of my code

- Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [x] Bug fixes

- [x] Proposed changes are described in the CHANGELOG.md

- [ ] Relevant unit tests have been added

### CODE REVIEW

File: src/main/scala/io/viash/wrapper/BashWrapper.scala [hunk 1]
```diff
@@ -117,6 +117,11 @@ object BashWrapper {
     mods: BashWrapperMods = BashWrapperMods(),
     debugPath: Option[String] = None
   ): String = {
+    // Escape substrings with pipe characters, meant to be used when using stripMargin.
+    // If the very first substring also starts with a pipe, strip the escaping off again as it will either become part of a previous string
+    // or would have its own | from the multiline string, and we don't want double pipes.
+    def escapePipes(s: String) = s.split("\n").map(_.replaceFirst("^(\\s*\\|)", "|$1")).mkString("\n").stripPrefix("|")
```
Comment (rcannood) [inline src/main/scala/io/viash/wrapper/BashWrapper.scala:123]: This might not work when the first line starts with a pipe already because it will result in double pipes, correct?

Comment (Grifs) [reply src/main/scala/io/viash/wrapper/BashWrapper.scala:123]: True! But that is why the `.stripPrefix("|")` is there

Comment (rcannood) [reply src/main/scala/io/viash/wrapper/BashWrapper.scala:123]: When comparing:

```scala
x.split("\n").map(_.replaceFirst("^(\\s*\\|)", "|$1")).mkString("\n").stripPrefix("|")
```

    val res1: String =
    |foo
    | | one
    bar

**Review by rcannood — APPROVED** [review]
