### PR TITLE
Fix empty lines being added when running viash config inject

### LINKED ISSUE #377: `viash config injects` adds an extra new line before the code block
If one were to run `viash config inject` multiple times, the extra new lines keep adding up.

### PR DESCRIPTION
**Pull request by Grifs**
## Describe your changes
Check whether the mods.header is empty to prevent adding it as an empty line.
Added an extra check in the e2e config inject test_languages testbench

## Issue ticket number and link
Closes #377 

## Checklist before requesting a review
- [x] I have performed a self-review of my code

- Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [x] Bug fixes

- [x] Proposed changes are described in the CHANGELOG.md

- [x] Relevant unit tests have been added

### CODE REVIEW

File: src/main/scala/io/viash/functionality/resources/Script.scala [hunk 1]
```diff
@@ -60,7 +60,10 @@ trait Script extends Resource {
           Array(companion.commentStr + companion.commentStr + " VIASH END") ++
           lines
         }
-      val li2 = Array(mods.header) ++ li ++ Array(mods.footer)
+      val li2 = mods.header match {
+          case "" => li :+ mods.footer
+          case _ => mods.header +: li :+ mods.footer
+        }
```
Comment (rcannood) [inline src/main/scala/io/viash/functionality/resources/Script.scala:66]: Why not do the same for the footer?

**Review by rcannood — COMMENTED** [review]
Thanks for picking this up! One minor question / comment.

**Review by rcannood — APPROVED** [review]
