### PR TITLE
Fix an issue where if the first resource is not a script, the resource is silently dropped

### LINKED ISSUE #650: [BUG] Resources that are specified before the script resource are silently ignored.
### What happened?

When a resources is specified before the first script resource, this resource is silently ignored.

### Steps to reproduce

```
mkdir -p /tmp/test_bug
cd /tmp/test_bug
cat > _viash.yaml << 'HERE'
viash_version: 0.8.4

source: src
target: target
HERE


mkdir -p src/dummycomponent

cat > src/dummycomponent/config.vsh.yaml << 'HERE'
functionality:
  name: myscript
  namespace: "dummycomponent"
  resources:
    - path: /foo.txt
    - type: bash_script
      path: script.sh
      text: |
        ls .

  test_resources:
    - type: bash_script
      path: test.sh
      text: |
        exit 0
platforms:
  - type: docker
    image: ubuntu:latest
  - type: native
  - type: nextflow
HERE

viash ns test -p native -q myscript
```

### Expected behavior

A warning or error is reported.

### Relevant log output

```
viash ns test -p native -q myscript
The working directory for the namespace tests is /tmp/viash_ns_test12536764874782085391
           namespace        functionality             platform            test_name exit_code duration               result
      dummycomponent             myscript               native                start
      dummycomponent             myscript               native              test.sh         0        0              SUCCESS
All 1 configs built and tested successfully
```

### Version

- OS: Ubuntu 22.04 LTS
- Viash 0.8.4

### Possible solution

_No response_

### Confirmation

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided clear and concise information about the bug.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Grifs**
## Describe your changes

Fix an issue where if the first resource is not a script, the resource is silently dropped

## Related issue(s)

Closes #650 

## Type of Change

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New functionality (non-breaking change which adds functionality)
- [ ] Major change (non-breaking change which modifies existing functionality)
- [ ] Minor change (non-breaking change which does not modify existing functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

## Checklist

Requirements:

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc.
- [x] I have performed a self-review of my code by checking the "Changed Files" tab.
- [x] My code follows the code style of this project.

Tests:

- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

Documentation:

- [x] Proposed changes are described in the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/main/scala/io/viash/functionality/Functionality.scala [hunk 1]
```diff
@@ -372,8 +372,10 @@ case class Functionality(
     }
   def mainCode: Option[String] = mainScript.flatMap(_.read)
   // provide function to use resources.tail but that allows resources to be an empty list
+  // If mainScript ends up being None because the first resource isn't a script, return the whole list
   def additionalResources = resources match {
-    case _ :: tail => tail
+    case head :: tail if head.isInstanceOf[Script] => tail
+    case list if list.nonEmpty => list
     case _ => List.empty[Resource]
```
Comment (rcannood) [inline src/main/scala/io/viash/functionality/Functionality.scala:379]: We can combine the last two cases, no?

```suggestion
    case list => list
```

**Review by rcannood — COMMENTED** [review]
LGTM! Minor suggestion

**Comment by Grifs** [comment]
> LGTM! Minor suggestion

Right, I was thinking of other edge cases ... which totally don't happen in Scala :stuck_out_tongue:

**Review by rcannood — APPROVED** [review]
