### PR TITLE
Fix/resolved paths in config view

### LINKED ISSUE #654: [BUG] Viash 0.9 doesn't output the resource parent
### What happened?

Viash 0.9 no longer outputs the parent of a resource when running `viash config view`

### Steps to reproduce

Create a config `src/foo/config.vsh.yaml` with contents:

```yaml
name: foo
resources:
  - type: bash_script
    path: script.sh
  - path: /project_relative.txt
  - path: ../relative.txt
```

Run `viash config view`:

```yaml
name: "foo"
resources:
- type: "bash_script"
  path: "script.sh"
  is_executable: true
- type: "file"
  path: "project_relative.txt"
- type: "file"
  path: "relative.txt"
```

According to the resulting `viash config view`, it appears as if the `README.md` is relative to the foo component, which is not the case.

With Viash < 0.9, the output of `viash config view` is the following:

```yaml
functionality:
  name: "foo"
  resources:
    - type: "bash_script"
      path: "script.sh"
      is_executable: true
      parent: "file:/home/rcannood/workspace/biobase/src/foo/"
    - type: "file"
      path: "project_relative.txt"
      parent: "file:///home/rcannood/workspace/biobase/"
    - type: "file"
      path: "relative.txt"
      parent: "file:/home/rcannood/workspace/biobase/src/"
```

I understand and agree that the parent attribute is not something that we want to output.

### Expected behavior

Having said that, I would expect the output of `viash config view` to contain file paths that can actually be resolved.

That is, the output of `viash config view` and `viash ns list` show the original values stored in the viash config:

```yaml
name: "foo"
resources:
- type: "bash_script"
  path: "script.sh"
  is_executable: true
- type: "file"
  path: "/project_relative.txt"
- type: "file"
  path: "../relative.txt"
```

However, when a `viash build` or `viash ns build` is run, the resulting `.config.vsh.yaml` _should_ now contain the following info, because the resource files are now available relative to the .config.vsh.yaml.

```yaml
name: "foo"
resources:
- type: "bash_script"
  path: "script.sh"
  is_executable: true
- type: "file"
  path: "project_relative.txt"
- type: "file"
  path: "relative.txt"
```

### Relevant log output

_No response_

### Version

0.9.0-RC2

### Possible solution

This could be solved in a variety of ways. Either we could:

* Not do any resource path resolution when running viash config view or viash ns list
* Rename a resource's `parent` field to `uri` and make it store the full uri instead of the parent directory uri. That way, we can let the `path` field simply retain the unmodified original data.
* Use different classes to denote whether the resource has not been resolved (string) or has been resolved (string and uri to parent dir / resource itself).

### Confirmation

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided clear and concise information about the bug.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Grifs**
## Describe your changes

Don't change `path` while reading the config's resources.
Add `resolvedPath` method to implement the previous function.
All `path` use is replaced with `resolvedPath`.
Update `path` just before writing it to file during a `viash [ns] build`

## Related issue(s)

Closes #654 

## Type of Change

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New functionality (non-breaking change which adds functionality)
- [ ] Major change (non-breaking change which modifies existing functionality)
- [ ] Minor change (non-breaking change which does not modify existing functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

## Checklist

Requirements:

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc.
- [x] I have performed a self-review of my code by checking the "Changed Files" tab.
- [x] My code follows the code style of this project.

Tests:

- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

Documentation:

- [x] Proposed changes are described in the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/main/scala/io/viash/config/resources/Resource.scala [hunk 1]
```diff
@@ -96,6 +96,25 @@ trait Resource {
     }
   }
 
+  def resolvedPath: Option[String] = {
```
Comment (rcannood) [inline src/main/scala/io/viash/config/resources/Resource.scala:99]: Could you add some inline or function-level docs to describe in which order the path gets resolved? :bow:

**Review by rcannood — COMMENTED** [review]
Thanks for taking care of this! It's great that this issue was resolved before 0.9.0 gets released.

Would it be possible to add a test that checks whether the path makes sense when running `viash config view` and after running `viash build`? :grimacing:

**Review by rcannood — APPROVED** [review]
Thanks! LGTM!
